//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coralcode.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InValidWords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InValidWords() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coralcode.Framework.Resources.InValidWords", typeof(InValidWords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /聚宝金融集团/房地产/地产商/地产开发/江贼民/tataUFO/益投网贷/限量版/返点卡/周年/钥匙扣/天水生活网/美乐商城/中国牛仔服饰网/大奖/一等奖/二等奖/特等奖/代开/全民富联盟/艾美美妆/华荣超市/欢乐庆店/2周年/真人/登录官网/特约/赞助/促销/李克强/央企/中移动/常务会议/不整顿/任人唯亲/K粉/地产/中奖/安理会/白粉/绑架/报仇/抗议/暴乱/暴政/爆炸装置/北京当局/精液/避孕套/藏独/操B/操逼/操你/抽奖/慈善/贷款/弹劾/弹药/党专制/倒卖/盗卖/抵押/抵制/电信公司/动乱/毒品/毒瘾/放款/坟墓/封杀/封锁/睾丸/个股/共产党/股指/龟头/国家领导/国家主席/国家总统/黑火药/黑社会/护法/火葬/鸡巴/集会/监听器/监狱/讲法/可卡因/刻章/恐怖主义/联通公司/两性视频/流氓/留学/六合彩/楼盘/卵巢/乱伦/轮奸/裸体/迷昏药/迷魂药/迷奸药/谋杀/穆斯林/你妈/牛股/牛市/迫害/菩萨/枪毙/枪支/强暴/强奸/抢购/抢劫/情色/全球通/权威/人大代表/人权/蹂躏/乳房/软禁/三级片/三陪/三唑仑/三唑伦/散户/桑拿/骚逼/色情/杀人/杀手/傻逼/少妇/射精/伸冤/尸/示威/兽 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SmsInvalidWords {
            get {
                return ResourceManager.GetString("SmsInvalidWords", resourceCulture);
            }
        }
    }
}
